# Generated by Django 3.0.8 on 2020-07-22 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fmodel',
            old_name='content',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='fmodel',
            name='grade',
            field=models.TextField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
