# Generated by Django 3.0.8 on 2020-07-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200722_1447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fmodel',
            new_name='availableCourses',
        ),
    ]
