# Generated by Django 3.0.8 on 2020-07-22 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200722_1449'),
    ]

    operations = [
        migrations.DeleteModel(
            name='availableCourses',
        ),
    ]
