# Generated by Django 3.0.8 on 2020-09-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200722_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=250)),
                ('lName', models.CharField(max_length=250)),
                ('advisorName', models.CharField(max_length=250)),
                ('gradeYear', models.CharField(choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2)),
                ('addCourse', models.CharField(max_length=250)),
                ('addCourseBlock', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=1)),
                ('addCourseTerm', models.CharField(choices=[('Sem1', 'Sem1'), ('Sem2', 'Sem2'), ('Yearly', 'Yearly'), ('Fall', 'Fall'), ('Winter', 'Winter'), ('Spring', 'Spring')], max_length=6)),
                ('dropCourse', models.CharField(max_length=250)),
                ('dropCourseBlock', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=1)),
                ('dropCourseTerm', models.CharField(choices=[('Sem1', 'Sem1'), ('Sem2', 'Sem2'), ('Yearly', 'Yearly'), ('Fall', 'Fall'), ('Winter', 'Winter'), ('Spring', 'Spring')], max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='another',
        ),
    ]
