# Generated by Django 3.0.8 on 2020-09-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200930_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodel',
            old_name='addCourse',
            new_name='_addCourse',
        ),
    ]
