# Generated by Django 3.0.8 on 2020-09-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200930_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='_addCourse',
            field=models.CharField(db_column='addCourse', max_length=250),
        ),
    ]
