# Generated by Django 3.1.1 on 2020-10-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200930_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='_addCourse',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='addCourse',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='addCourseBlock',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='addCourseTerm',
            field=models.CharField(choices=[('Sem1', 'Sem1'), ('Sem2', 'Sem2'), ('Yearly', 'Yearly'), ('Fall', 'Fall'), ('Winter', 'Winter'), ('Spring', 'Spring')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='advisorName',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='dropCourse',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='dropCourseBlock',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='dropCourseTerm',
            field=models.CharField(choices=[('Sem1', 'Sem1'), ('Sem2', 'Sem2'), ('Yearly', 'Yearly'), ('Fall', 'Fall'), ('Winter', 'Winter'), ('Spring', 'Spring')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='fName',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='gradeYear',
            field=models.CharField(choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='lName',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
