# Generated by Django 3.0.8 on 2020-10-23 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_avaiablecourses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='avaiableCourses',
            new_name='availableCourses',
        ),
    ]
