# Generated by Django 3.0.8 on 2020-10-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201023_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablecourses',
            name='coursecredit',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availablecourses',
            name='coursename',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
