# Generated by Django 3.0.8 on 2020-10-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201023_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablecourses',
            name='courseblock',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
