# Generated by Django 3.0.8 on 2020-10-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201023_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablecourses',
            name='isavailable',
            field=models.CharField(default='yes', max_length=250),
        ),
    ]
